# Generated by Django 4.1.1 on 2022-11-04 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'usuário'},
        ),
    ]
